### PR TITLE
:bug: `TestDialWithBackoff` work without special environment

### LINKED ISSUE #2401: `TestDialWithBackoff` from `network/transports_test.go` fails by not recognizing expected error outside of CI
## Expected Behavior

Test should pass without errors on any environment.

## Actual Behavior

Test fails with:

```shell
$ gotestsum -f testname -- -race -count=1 -run 'TestDialWithBackoff' ./network
=== RUN   TestDialWithBackoff
    transports_test.go:91: Error = dial tcp4 198.18.0.254:8888: connect: network is unreachable, want: timed out dialing(...)
--- FAIL: TestDialWithBackoff (0.00s)
FAIL network.TestDialWithBackoff (0.00s)
FAIL network

=== Failed
=== FAIL: network TestDialWithBackoff (0.00s)
    transports_test.go:91: Error = dial tcp4 198.18.0.254:8888: connect: network is unreachable, want: timed out dialing(...)

DONE 1 tests, 1 failure in 0.489s
```

## Steps to Reproduce the Problem

1. `gotestsum -f testname -- -race -count=1 -run 'TestDialWithBackoff' ./network`

## Additional Info

The test is using a special address `198.18.0.254:8888` that looks to work on the CI environment. I think a good idea would be to refactor tests to work on every environment, cutting this external dependency.

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :bug: `TestDialWithBackoff` work without special environment

/kind bug

Fixes #2401

### CODE REVIEW

**Comment by cardil** [comment]
The unit test failures [1486341657388388352](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_pkg/2402/pull-knative-pkg-unit-tests/1486341657388388352) look unrelated:

/test pull-knative-pkg-unit-tests

File: network/transports.go [hunk 1]
```diff
@@ -54,6 +54,9 @@ var backOffTemplate = wait.Backoff{
 	Steps:    15,
 }
 
+// ErrTimeoutDialing when the timeout is reached after set amount of time.
+var ErrTimeoutDialing = errors.New("timed out dialing")
```
Comment (dprotaso) [inline network/transports.go:58]: Rather than introduce a new error maybe we can return `context.DeadlineExceeded`

**Review by dprotaso — CHANGES_REQUESTED** [review]

File: network/transports_test.go [hunk 2]
```diff
@@ -68,35 +74,77 @@ func TestHTTPRoundTripper(t *testing.T) {
...
+func testDialWithBackoffTimeout(t *testing.T) {
 	// Make the test short.
 	bo := backOffTemplate
-	bo.Steps = 2
+	bo.Steps = 1
+	bo.Duration = time.Millisecond
 
-	// Timeout. Use special testing IP address.
-	c, err = dialBackOffHelper(context.Background(), "tcp4", "198.18.0.254:8888", bo, sleepTO)
+	// Timeout. Use non-routable IP. See: https://stackoverflow.com/a/31581323/844449
```
Comment (evankanderson) [inline network/transports_test.go:103]: One of the [documentation IP ranges](https://datatracker.ietf.org/doc/html/rfc5737#section-3) (or a localhost IP like `127.200.100.0`) might make more sense than private IP space (and all are better than some real IP address belonging to Oracle, so thanks for fixing that!).

Comment (cardil) [reply network/transports_test.go:103]: Localhost's range isn't a good idea. We may hit, by chance, the port being open.

File: network/transports_test.go [hunk 3]
```diff
@@ -68,35 +74,77 @@ func TestHTTPRoundTripper(t *testing.T) {
...
-	// Nobody's listening on a random port. Usually.
-	c, err := DialWithBackOff(context.Background(), "tcp4", "127.0.0.1:41482")
-	if err == nil {
-		c.Close()
-		t.Error("Unexpected success dialing")
+	t.Parallel()
+	t.Run("ConnectionRefused", testDialWithBackoffConnectionRefused)
+	t.Run("Timeout", testDialWithBackoffTimeout)
+	t.Run("Success", testDialWithBackoffSuccess)
+}
```
[the remark this answers is not in the document]
Comment (cardil) [reply network/transports_test.go:85]: In my opinion, why I wrote it like this, it's more organized. In reports as well.

The subtests could be executed as easily as root level ones. And we can ensure the test will run fast thanks to parallelization.

File: network/transports.go (hunk 1 above)
Comment (cardil) [reply network/transports.go:58]: This error type is introduced to not change the final error message. See the change in line 97:

```golang
return nil, fmt.Errorf("%w after %.2fs", ErrTimeoutDialing, elapsed.Seconds())
```

By introducing this error, consumers of this package could properly do the error checking using types:


```golang
if errors.Is(err, network.ErrTimeoutDialing) {
  // do some
}
```

instead of current dodgy string checking:


```golang
if string.Contains(err.Error(), "timed out dialing")) {
  // do some
}
```

File: network/transports_test.go [hunk 4]
```diff
@@ -68,35 +74,77 @@ func TestHTTPRoundTripper(t *testing.T) {
...
+
+func findUnusedPortOrFail(tb testing.TB) int {
+	tb.Helper()
+	addr, err := net.ResolveTCPAddr("tcp", "localhost:0")
+	if err != nil {
+		tb.Fatal(err)
+	}
+
+	l, err := net.ListenTCP("tcp", addr)
```
[the remark this answers is not in the document]
Comment (cardil) [reply network/transports_test.go]: Done

File: network/transports_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (cardil) [reply network/transports_test.go]: Also, now those cases are reused by regular and TLS version of the test.

**Comment by evankanderson** [comment]
Rather than using a likely-non-routable IP, how about using `Listen`'s backlog to force a timeout? (This is similar to the localhost IP range suggestion, but more likely to consistently work)

https://github.com/cardil/knative-pkg/pull/1

Note that both this PR and the current state in main don't work on Windows, with similar errors:

```
--- FAIL: TestDialWithBackoff (0.17s)
    --- FAIL: TestDialWithBackoff/ConnectionRefused (0.09s)
        transports_test.go:107: Unexpected error: timed out dialing after 0.09s
--- FAIL: TestDialTLSWithBackoff (0.19s)
    --- FAIL: TestDialTLSWithBackoff/ConnectionRefused (0.09s)
        transports_test.go:107: Unexpected error: timed out dialing after 0.09s
```

As a side note, putting all of these in one test makes it harder (for example) to run just the `DialWithBackoffTimout` test from VSCode -- you can click on "run test" above methods named `TestFoo` to run just that test, but in this case, you have to run the `TestDialWithBackoff` tests as a whole.

**Comment by cardil** [comment]
> Rather than using a likely-non-routable IP, how about using `Listen`'s backlog to force a timeout? [cardil#1](https://github.com/cardil/knative-pkg/pull/1)

Interesting. I'll continue on this next week.

> Note that both this PR and the current state in main don't work on Windows, with similar errors

I did run those tests multiple times, but apparently they also failed on Prow. It looks to me like your solution could help. Thanks! I'll take a look next week.

> As a side note, putting all of these in one test makes it harder to run just one test

That's a bummer. I use Goland, and there I could easily execute those subtests. VSCode should also have this feature.

Screenshot from 2022-04-22 22-40-59

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve
