### PR TITLE
Fix panic on DeletedFinalStateUnknown in ConfigMap informer

### LINKED ISSUE #3220: ConfigMap informer panics with DeletedFinalStateUnknown type assertion
**Description:**
The `InformedWatcher` in `knative/pkg/configmap/informer/informed_watcher.go` crashes when handling `cache.DeletedFinalStateUnknown` objects during ConfigMap deletion events.

**Error:** 
`panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.ConfigMap`

**Impact:**
- Causes webhook pods to crash and restart repeatedly

**Root Cause:**
Unsafe type assertion in event handlers doesn't handle DeletedFinalStateUnknown objects

**Proposed Fix:**
Add safe type assertion with DeletedFinalStateUnknown handling

### PR DESCRIPTION
**Pull request by anjalii-28**
Fixes #3220

### CODE REVIEW

**Comment by anjalii-28** [comment]
This PR fixes the panic caused by DeletedFinalStateUnknown in the ConfigMap informer
and adds tests to ensure delete events are handled safely.

PTAL, thanks!

**Comment by dprotaso** [comment]
You'll need to sign the CLA - see this comment https://github.com/knative/pkg/pull/3301#issuecomment-3649871422

**Comment by dprotaso** [comment]
/lgtm
/approve

Thanks for the change - let me know when you sort out the EasyCLA

File: configmap/informer/informed_watcher_test.go [hunk 1]
```diff
@@ -487,3 +488,140 @@ func TestWatchWithDefaultAfterStart(t *testing.T) {
 		t.Fatalf("foo1.count = %v, want %d", got, want)
 	}
 }
+
```
Comment (creydr) [inline configmap/informer/informed_watcher_test.go:491]:
```suggestion
```
I guess this was in 33ffc8e86ef31a034fb27ca2b8e7b39a59a04669 to trigger the easyCLA check. 
For the future: IIRC this can also be triggered through some command like `/easycla`

Comment (anjalii-28) [reply configmap/informer/informed_watcher_test.go:491]: @creydr removed this extra line, but somehow easyCLA check is not passing. 
Can you help ?

Comment (creydr) [reply configmap/informer/informed_watcher_test.go:491]: In https://github.com/knative/pkg/pull/3301#issuecomment-3649871422 it says:

> * ❌ The email address for the commit ([f95d534](https://github.com/knative/pkg/commit/f95d5340e39c5f4af3b020e10d5c459938cc84ea)) is not linked to the GitHub account, preventing the EasyCLA check. Consult [this Help Article](https://linuxfoundation.atlassian.net/wiki/spaces/LP/pages/160923756/Missing+ID+on+Commit+but+I+have+an+agreement+on+file) and [GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve. (To view the commit's email address, add .patch at the end of this PR page's URL.) For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

So you need to make sure your first commit (f95d5340e39c5f4af3b020e10d5c459938cc84ea) comes from an email, linked to your GitHub user. Check for example on the linked help articles how to do it

**Comment by dprotaso** [comment]
easy cla isn't satisfied - unsure if you need to sign older commits?

```
git rebase --signoff HEAD~N 
```

Generally though I thought it was tied to the email in your github account

**Comment by dprotaso** [comment]
I'm not really an EasyCLA expert so you'll want to open an issue here: https://github.com/linuxfoundation/easycla

**Comment by dprotaso** [comment]
@anjalii-28 any luck with the CLA?

File: configmap/informer/informed_watcher_test.go (hunk 1 above)
Comment (anjalii-28) [reply configmap/informer/informed_watcher_test.go:491]: Thanks for helping, easyCLA is now sorted.

**Comment by anjalii-28** [comment]
> @anjalii-28 any luck with the CLA?

Yes, easyCLA is now sorted, please review and approve the PR.

**Comment by anjalii-28** [comment]
@creydr  could you please review the PR
