### PR TITLE
Fail reconciliation when a ReconcileEvent is wrapped inside an error

### LINKED ISSUE #1266: Implement retryable API events in injected Reconcilers
/area API
/kind feature

I like the way generated Reconcilers can extract an event from the returned error and record that event via the injected EventRecorder. 👍 

Unfortunately, there is no way to return an "error" event _and_ retry the reconciliation. What I want is to be able to return an actual error while still being able to provide a better classification than "InternalError".

I suggest we support wrapping events inside a specific error type, similarly to how `controller.NewPermanentError` creates a special type of error, and take that as a hint that the reconciliation should be retried after the event is recorded.

I'm gonna look into this over the weekend unless someone objects.

/assign

### PR DESCRIPTION
**Pull request by antoineco**
Allows errors to be re-enqueued event if they wrap a `ReconcilerEvent`.

The event is recorded whether it's wrapped or not, but a non-wrapped `ReconcilerEvent` is not considered as a `Reconcile()` error (current behaviour).

Too bad Kubernetes doesn't have a `corev1.EventTypeError`, _sighs_.

Closes #1266

---

examples:

```golang
// causes a re-enqueue
myevent := reconciler.NewEvent(corev1.EventTypeWarning, oopsReason, "oops")
return fmt.Errorf("this is bad: %w", myEvent)
```
```golang
// does NOT cause a re-enqueue
return reconciler.NewEvent(corev1.EventTypeWarning, oopsReason, "oops")
```
```golang
// reminder: permanentError can be used to prevent a re-enqueue regardless
// of the contents of the error
myevent := reconciler.NewEvent(corev1.EventTypeWarning, oopsReason, "oops")
return controller.NewPermanentError(fmt.Errorf("this is bad: %w", myEvent))
```

### CODE REVIEW

**Comment by antoineco** [comment]
@dprotaso @n3wscott friendly ping.

File: codegen/cmd/injection-gen/generators/reconciler_reconciler.go [hunk 1]
```diff
@@ -339,13 +339,19 @@ func (r *reconcilerImpl) Reconcile(ctx {{.contextContext|raw}}, key string) erro
 		if reconciler.EventAs(reconcileEvent, &event) {
```
Comment (n3wscott) [inline codegen/cmd/injection-gen/generators/reconciler_reconciler.go:339]: Let's follow up by moving the reconciler event logic out of the generated code and into the reconciler base that @whaught is working on.

Comment (n3wscott) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:339]: it would be nice to write some tests on this area of the codebase.

Comment (antoineco) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:339]: Good idea, I'll see how I can help.
