### PR TITLE
Genreconciler properly generates reconciler for Resources with Status

### LINKED ISSUE #2003: Genreconciler generates invalid code when generating reconciler for corev1.Secret
## Expected Behavior

Generating the reconciler for `corev1.Secret` generates valid code

## Actual Behavior

Generating the reconciler for `corev1.Secret` generates invalid code that uses the field `Status`, which secret does not contain. E.g.:

```
func (r *reconcilerImpl) updateStatus(ctx context.Context, existing *v1.Secret, desired *v1.Secret) error {
	existing = existing.DeepCopy()
	return reconciler.RetryUpdateConflicts(func(attempts int) (err error) {
		// The first iteration tries to use the injectionInformer's state, subsequent attempts fetch the latest state via API.
		if attempts > 0 {

			getter := r.Client.CoreV1().Secrets(desired.Namespace)

			existing, err = getter.Get(ctx, desired.Name, metav1.GetOptions{})
			if err != nil {
				return err
			}
		}

		// If there's nothing to update, just return.
		if reflect.DeepEqual(existing.Status, desired.Status) {
			return nil
		}

		if diff, err := kmp.SafeDiff(existing.Status, desired.Status); err == nil && diff != "" {
			logging.FromContext(ctx).Debug("Updating status with: ", diff)
		}

		existing.Status = desired.Status

		updater := r.Client.CoreV1().Secrets(existing.Namespace)

		_, err = updater.UpdateStatus(ctx, existing, metav1.UpdateOptions{})
		return err
	})
}
```

## Steps to Reproduce the Problem

1. Add `Secret` to the list here: https://github.com/knative/pkg/blob/0d31134d5f4e37a2d44392ec8fb8790e2dd4f7e7/hack/update-codegen.sh#L52
2. Run `./hack/update-codegen.sh`
3. Try to build the generated code

## Additional Info
It seems like the genreconciler always assumes there is a `Status` in every input `Resource`

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #2003

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

# Changes

- :gift: Genreconciler properly generates reconciler for Resources with Status
- Added generated Secret reconciler

### CODE REVIEW

File: codegen/cmd/injection-gen/generators/packages.go [hunk 1]
```diff
@@ -737,3 +739,12 @@ func versionDuckPackages(basePackage string, groupPkgName string, gv clientgenty
 	}
 	return vers
 }
+
+func hasStatus(t *types.Type) bool {
+	for _, member := range t.Members {
+		if member.Name == "Status" {
```
Comment (markusthoemmes) [inline codegen/cmd/injection-gen/generators/packages.go:745]: nice!

File: codegen/cmd/injection-gen/generators/reconciler_controller.go [hunk 2]
```diff
@@ -264,9 +266,9 @@ func NewImpl(ctx {{.contextContext|raw}}, r Interface{{if .hasClass}}, classValu
 		if opts.AgentName != "" {
 			agentName = opts.AgentName
 		}
-		if opts.SkipStatusUpdates {
+		{{if .hasStatus}}if opts.SkipStatusUpdates {
```
Comment (markusthoemmes) [inline codegen/cmd/injection-gen/generators/reconciler_controller.go:269]: can we not have newline around?

File: codegen/cmd/injection-gen/generators/reconciler_reconciler.go [hunk 3]
```diff
@@ -429,21 +435,21 @@ func (r *reconcilerImpl) Reconcile(ctx {{.contextContext|raw}}, key string) erro
 		if resource, err = r.setFinalizerIfFinalizer(ctx, resource); err != nil {
 			return {{.fmtErrorf|raw}}("failed to set finalizers: %w", err)
 		}
-		{{if .isKRShaped}}
+		{{if .hasStatus}}{{if .isKRShaped}}
```
Comment (markusthoemmes) [inline codegen/cmd/injection-gen/generators/reconciler_reconciler.go:438]: Doesn't KRShaped include status? Feels like a redundant check.

File: codegen/cmd/injection-gen/generators/reconciler_reconciler.go [hunk 4]
```diff
@@ -429,21 +435,21 @@ func (r *reconcilerImpl) Reconcile(ctx {{.contextContext|raw}}, key string) erro
...
 		}
-		{{end}}
+		{{end}}{{end}}
 
 		// Reconcile this copy of the resource and then write back any status
 		// updates regardless of whether the reconciliation errored out.
 		reconcileEvent = do(ctx, resource)
 
-		{{if .isKRShaped}}
+		{{if .hasStatus}}{{if .isKRShaped}}
```
Comment (markusthoemmes) [inline codegen/cmd/injection-gen/generators/reconciler_reconciler.go:448]: this too

File: codegen/cmd/injection-gen/generators/reconciler_reconciler.go (hunk 3 above)
Comment (slinkydeveloper) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:438]: What `isKRShaped` means in first instance? :smiley:

Comment (markusthoemmes) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:438]: https://github.com/knative/pkg/blob/0d31134d5f4e37a2d44392ec8fb8790e2dd4f7e7/apis/duck/v1/kresource_type.go#L31-L39

Comment (slinkydeveloper) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go]: Thanks, changed!

**Comment by slinkydeveloper** [comment]
```
=== RUN   TestMetricsExport/OpenCensus
    e2e_test.go:235: Created exporter at localhost:12345
    logger.go:130: 2021-01-28T15:19:27.710Z	INFO	metrics/exporter.go:161	Flushing the existing exporter before setting up the new exporter.
    logger.go:130: 2021-01-28T15:19:27.797Z	INFO	metrics/opencensus_exporter.go:56	Created OpenCensus exporter with config:	{"config": {}}
    logger.go:130: 2021-01-28T15:19:27.798Z	INFO	metrics/exporter.go:174	Successfully updated the metrics exporter; old config: &{knative.dev/serving testComponent prometheus 1000000000 <nil> <nil>  false 19090 0.0.0.0 false   {   false}}; new config &{knative.dev/serving testComponent opencensus 1000000000 <nil> <nil> localhost:12345 false 0  false   {   false}}
    e2e_test.go:273: Timeout reading input
    e2e_test.go:279: Unexpected OpenCensus exports (-want +got):
          []metrics.metricExtract(Inverse(Sort, []string{
        - 	"knative.dev/serving/testComponent/global_export_counts<>:2",
        - 	"knative.dev/serving/testComponent/resource_global_export_count<>:2",
          	`knative.dev/serving/testComponent/testing/value<project="p1",rev`...,
          	`knative.dev/serving/testComponent/testing/value<project="p1",rev`...,
          }))
    --- FAIL: TestMetricsExport/OpenCensus (5.20s)
```

Not related to this PR

/retest

**Review by markusthoemmes — APPROVED** [review]
Can you run this against serving or eventing to show that this doesn't cause diffs for the existing types? Or at least no meaningful diffs (whitespace is fine obvs.)

LGTM otherwise!

/assign @n3wscott

**Comment by slinkydeveloper** [comment]
> Can you run this against serving or eventing to show that this doesn't cause diffs for the existing types? Or at least no meaningful diffs (whitespace is fine obvs.)

Note that it doesn't cause any change to the namespace and deployment controllers generated here :)

**Comment by markusthoemmes** [comment]
Right but a quick sniff test wouldn't hurt to check it works against our CRDs. It'll prolly be fine but :man_shrugging:.

**Comment by slinkydeveloper** [comment]
No changes in eventing:

```
(issues/4515_spec)⚡ % git status                                                                                                                                               ~/go/src/knative.dev/eventing
Sul branch issues/4515_spec
Il tuo branch è aggiornato rispetto a 'origin/issues/4515_spec'.

Modifiche non nell'area di staging per il commit:
  (usa "git add <file>..." per aggiornare gli elementi di cui sarà eseguito il commit)
  (usa "git restore <file>..." per scartare le modifiche nella directory di lavoro)
        modificato:             go.mod
        modificato:             go.sum
        modificato:             vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
        modificato:             vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
        modificato:             vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
        modificato:             vendor/knative.dev/pkg/hack/update-codegen.sh
        modificato:             vendor/modules.txt

nessuna modifica aggiunta al commit (usa "git add" e/o "git commit -a")
```

File: codegen/cmd/injection-gen/generators/reconciler_reconciler.go [hunk 5]
```diff
@@ -351,10 +357,10 @@ func NewReconciler(ctx {{.contextContext|raw}}, logger *{{.zapSugaredLogger|raw}
 		}
 		if opts.FinalizerName != "" {
 			rec.finalizerName = opts.FinalizerName
-		}
+		}{{if .hasStatus}}
```
Comment (vagababov) [inline codegen/cmd/injection-gen/generators/reconciler_reconciler.go:360]: can we reflow this and {{end}} on individual lines?

Comment (slinkydeveloper) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:360]: If we do, it will generate non useful newlines, i prefer to avoid it

Comment (vagababov) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:360]: Who reads generated code? :)
This on the other side — is read :)

Comment (whaught) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:360]: I think `{{- end}}` will eat the whitespace and everybody wins

Comment (slinkydeveloper) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:360]: I tried with 

```
		{{if .hasStatus}}
		if opts.SkipStatusUpdates {
			rec.skipStatusUpdates = true
		}
		{{- end}}
```

But it changed all the generated code...

Comment (slinkydeveloper) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:360]: If possible, I would love to avoid changing all the generated code downstream for a new line

Comment (markusthoemmes) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go:360]:
```
		{{- if .hasStatus}}
		if opts.SkipStatusUpdates {
			rec.skipStatusUpdates = true
		}
		{{- end}}
```

should make everybody happy. Applies to another place a few lines above this as well.

Comment (slinkydeveloper) [reply codegen/cmd/injection-gen/generators/reconciler_reconciler.go]: This one did it!!!
