### PR TITLE
Spoof at the Resolver layer, not the Request layer

### LINKED ISSUE #621: Support spoofing for HTTPS
Currently, Spoofing is done at the request layer, meaning `http.Request.Host` and `http.Request.URL.Host` are modified. This doesn't work with HTTPS because `http.Request.URL.Host` must match the TLS certificate Common Name or Subject Alternative Names, and therefore cannot be tempered. The solution is to spoof at the DNS resolution.

See: https://github.com/knative/pkg/blob/master/test/spoof/spoof.go#L148 and https://github.com/google/certificate-transparency-go/blob/d5650005f3fc3b87ef669ac9b3a7e9d9f659ef69/x509/verify.go#L109.

## Expected Behavior
`SpoofingClient` will fail to contact a `https://` URL. 

## Actual Behavior
`SpoofingClient` will successfully contact an `https://` URL.

### PR DESCRIPTION
**Pull request by JRBANCEL**
Same as https://github.com/knative/pkg/pull/620 that was reverted.
The differences:
- Fixes the race condition by creating a new http.Transport before modifying it
- Public functions signatures are modified in a backward compatible way to minimize changes in knative.dev/serving
- Instead of requiring an http.Transport, use the functional options pattern

---

Fixes #621.

Currently, Spoofing is done at the request layer, meaning http.Request.Host and http.Request.URL.Host are modified. This doesn't work with HTTPS because http.Request.URL.Host must match the TLS certificate Common Name or Subject Alternative Names, and therefore cannot be tempered. The solution is to spoof at the DNS resolution.

### CODE REVIEW

File: test/request.go [hunk 1]
```diff
@@ -163,11 +176,19 @@ func WaitForEndpointStateWithTimeout(
 		return nil, err
 	}
 
+	var tOpts []spoof.TransportOption
 	for _, opt := range opts {
-		opt(req)
+		rOpt, ok := opt.(RequestOption)
```
Comment (vagababov) [inline test/request.go]: ``
if r, ok := opt.(RO); ok {
  r(req)
} else if r, ok := opt.(s.TO); ok {
  to = append(to, r)
}
```
It's one or the other, so if else or continue.

File: test/spoof/spoof.go [hunk 2]
```diff
@@ -82,72 +85,81 @@ type SpoofingClient struct {
...
+		fmt.Errorf("failed get the cluster endpoint: %v", err)
 	}
 
-	var err error
-	if sc.endpoint, err = ResolveEndpoint(kubeClientset, domain, resolvable, endpointOverride); err != nil {
-		return nil, err
+	// Spoof the hostname at the resolver level
+	dialContext := (&net.Dialer{}).DialContext
+	transport := &http.Transport{}
+	transport.DialContext = func(ctx context.Context, network, addr string) (conn net.Conn, e error) {
```
Comment (vagababov) [inline test/spoof/spoof.go]: These several lines _are_ a TransportOption ;-)

File: test/spoof/spoof.go [hunk 3]
```diff
@@ -82,72 +85,81 @@ type SpoofingClient struct {
...
+	endpoint, err := ResolveEndpoint(kubeClientset, domain, resolvable, endpointOverride)
+	if err != nil {
+		fmt.Errorf("failed get the cluster endpoint: %v", err)
 	}
 
-	var err error
-	if sc.endpoint, err = ResolveEndpoint(kubeClientset, domain, resolvable, endpointOverride); err != nil {
-		return nil, err
+	// Spoof the hostname at the resolver level
+	dialContext := (&net.Dialer{}).DialContext
```
Comment (vagababov) [inline test/spoof/spoof.go]: probably can be a package level var, since `DialContext` is safe for concurrent usage

File: test/spoof/spoof.go (hunk 2 above)
Comment (JRBANCEL) [reply test/spoof/spoof.go]: I somewhat agree, but if I do that, SpoofingClient becomes useless. It becomes just a empty wrapper around http.Client.
Ideally, we wouldn't need SpoofingClient and we could reuse the Prober code with options, but that's a much bigger change.

Comment (vagababov) [reply test/spoof/spoof.go]: Deleting code is always good :)

Comment (JRBANCEL) [reply test/spoof/spoof.go]: I'll tackle that later :-)
