### PR TITLE
Don't discard addressable resolver original errors

### LINKED ISSUE #2394: Addressable resolver discard original error when a lister factory fails
## Expected Behavior

The error is specific and the original error isn't discarded

## Actual Behavior

I get a generic error like:
`kafkachannels "Lister" not found`

## Additional Info

/kind bug

### PR DESCRIPTION
**Pull request by pierDipi**
Errors from the tracker or the addressable resolver factory
are discarded which isn't helpful for debugging since the
error is generic `kafkachannels "Lister" not found`.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

# Changes

- Don't discard addressable resolver original errors

/kind bug

Fixes #2394

### CODE REVIEW

File: resolver/addressable_resolver_test.go [hunk 1]
```diff
@@ -619,8 +621,8 @@ func TestURIFromObjectReferenceErrors(t *testing.T) {
 			if got, want := err2.Error(), tc.wantErr; got != want {
 				t.Errorf("Unexpected error (-want, +got) =\n%s", cmp.Diff(want, got))
 			}
-			if !cmp.Equal(err1, err2) {
-				t.Errorf("Idempotency fail: first err = %v, second err = %v", err1, err2)
```
Comment (pierDipi) [inline resolver/addressable_resolver_test.go:623]: Note: this comparison doesn't work for Go wrapped or multierr errors.

File: resolver/addressable_resolver.go [hunk 2]
```diff
@@ -169,17 +172,17 @@ func (r *URIResolver) URIFromObjectReference(ctx context.Context, ref *corev1.Ob
 		Namespace:  ref.Namespace,
 		Name:       ref.Name,
 	}, parent); err != nil {
-		return nil, apierrs.NewNotFound(gvr.GroupResource(), ref.Name)
+		return nil, multierr.Combine(err, apierrs.NewNotFound(gvr.GroupResource(), ref.Name))
```
Comment (lionelvillard) [inline resolver/addressable_resolver.go:175]: why not using go 1.13 wrap/unwrap feature?

Comment (pierDipi) [reply resolver/addressable_resolver.go]: The linter is not happy with this format 
```
fmt.Errorf("%s; %w", err.Error(), apierrs.NewNotFound(gvr.GroupResource(), ref.Name))
```

```
 Error: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors (errorlint)
  Error: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors (errorlint)
  Error: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors (errorlint)
```

**Review by rhuss — COMMENTED** [review]
Thanks !

/approve
/lgtm

File: resolver/addressable_resolver.go (hunk 2 above)
Comment (cardil) [reply resolver/addressable_resolver.go]: It should be:

```go
fmt.Errorf("%w: %v", apierrs.NewNotFound(gvr.GroupResource(), ref.Name), err)
```
