### PR TITLE
Fix potential deadlock when k8s client is used

### LINKED ISSUE #807: Potential deadlock in knative.dev/pkg/metrics when using k8s.io/client-go/kubernetes
When using knative.dev/metrics/pkg, the kubeclient has an unexpected dependency on the knative.dev/pkg/metrics pkg and its internal lock (metricsMux) that prevents the kubeclient from being used freely within the metrics pkg.

Here are the two uses of the metricsMux that don't play well.

knative.dev/pkg/metrics/exporter.go
- exporter.go protects its internal state, the current metrics config and current metrics exporter, with a Mutex (metricsMux) https://github.com/knative/pkg/blob/master/metrics/exporter.go#L28 
- Whenever exporter.go updates the exporter, it needs to obtain the lock to read internal state
- Updating the exporter also requires using the kubeclient to read a K8s Secret specified in the metrics config https://github.com/knative/pkg/blob/master/metrics/stackdriver_exporter.go#L177 
- Potentially other kubeclient things could be done in the future

k8s.io/client-go/
- The k8s.io/client-go/tools/metrics pkg provides a hook for users to record the latency of the kubernetes rest clients. https://github.com/kubernetes/client-go/blob/master/tools/metrics/metrics.go#L40-43
- knative.dev/metrics/pkg sets this hook 
 https://github.com/knative/pkg/blob/master/metrics/metrics.go#L115-126
- On every kubeclient request, the hook calls metrics.Record() https://github.com/knative/pkg/blob/master/metrics/record.go#L41 
- The call to metrics.Record() needs to obtains the knative.dev/pkg/metrics pkg's internal lock to read the metrics config

The effect of this is every call to kubeclient uses the metrics pkg to Record a metric, and needs to lock metricsMux. Every update to the metrics exporter needs to call the kubeclient, and needs to lock metricsMux.

This prevents fully locking the metrics exporter update section to prevent race conditions.

Ideally we find a way to make the kubeclient usable anywhere with the metrics package, or we make it very clear to developers that they cannot use it within a lock through a test that will fail or dev-oriented error.

## Expected Behavior
You can use the client-go kubeclient while locked with the metricsMux.

## Actual Behavior
Deadlock

## Steps to Reproduce the Problem
Within the knative.dev/pkg/metrics pkg
1. Add a call to metricsMux.Lock()
2. Within the lock scope, attempt to use the client-go kubeclient
3. Deadlock
```
import (
  corev1 "k8s.io/api/core/v1"
  metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
  "k8s.io/client-go/kubernetes"
  "k8s.io/client-go/rest"
}

func someFunc() {
  metricsMux.Lock()
  defer metricsMux.Unlock()
  config, _ := rest.InClusterConfig()
  kubeclient, _ := kubernetes.NewForConfig(config)

  kubeclient.CoreV1().Secrets("").Get("some-secret", metav1.GetOptions{})
  // Never reach here
}

## Additional Info

### PR DESCRIPTION
**Pull request by skonto**
# Changes

- Removes the global metrics config mutex to avoid a potential deadlock when k8s client is used due to the 
registered metrics hooks in the client.
- This PR preserves the previous semantics when managing the metrics config etc so it should be transparent from a user point of view.
- It follows the worker approach in the opencensus lib.

/kind bug

Fixes #807 

/cc @vagababov @evankanderson

### CODE REVIEW

**Comment by skonto** [comment]
`TestMetricsExport` fails again.

File: metrics/testing.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ const (
 
 // InitForTesting initialize the necessary global variables for unit tests.
 func InitForTesting() {
+	setupMetricsWorker()
```
Comment (vagababov) [inline metrics/testing.go:25]: I think this is already called due to `init`?

Comment (skonto) [reply metrics/testing.go:25]: Nope that was really weird because I thought init from the metrics packed (since it is imported) it would be call first but it does not. It fails with a nil pointer exception when it tries to access the mWorker.

Comment (skonto) [reply metrics/testing.go:25]: Cant reproduce it will update.

**Comment by skonto** [comment]
@evankanderson gentle ping.

File: metrics/exporter.go [hunk 2]
```diff
@@ -154,28 +158,14 @@ func UpdateExporter(ctx context.Context, ops ExporterOptions, logger *zap.Sugare
...
+		ctx:       ctx,
+		newConfig: newConfig,
+		done:      make(chan error),
 	}
-
-	setCurMetricsConfigUnlocked(newConfig)
-	return nil
+	mWorker.c <- updateCmd
+	err = <-updateCmd.done
+	return err
```
Comment (evankanderson) [inline metrics/exporter.go:168]: I think this can be `return <-updateCmd.done`

**Review by evankanderson — COMMENTED** [review]
Other than the unit test failure, this looks reasonable to me.

**Comment by evankanderson** [comment]
Running main and your branch 84 times, I see about an equivalent number of failures (8 vs 9(, but there seems to be a lot more output on failure with this PR, and I see a timeout/missing data failure in the OpenCensus export in addition to the `e2e_test.go:320` timeout on Prometheus errors. I'm willing to believe that the OpenCensus failure was a fluke and that this doesn't make the Prometheus failures any worse (though they seem much higher than I'd expect).

/retest
/lgtm
/approve

**Comment by skonto** [comment]
@evankanderson I have seen that test failing multiple times in my other pr #2005, left a comment [there](https://github.com/knative/pkg/pull/2005#issuecomment-776174080), so I am not sure if this is any different.
I will try to debug that and see if it can be fixed.
