### PR TITLE
Use go run to run codegen

### LINKED ISSUE #1294: update-codegen.sh produces inconsistent output
## Expected Behavior
Checking out master and running ./hack/update-codegen.sh should produce no changes.

## Actual Behavior
Running ./hack/update-codegen.sh produces changes to the generated controllers.

## Steps to Reproduce the Problem

1. Checkout the master branch.
2. Run ./hack/update-codegen.sh

## Additional Info
Using go 1.14.2

### PR DESCRIPTION
**Pull request by ian-mi**
Fixes #1294
cc @grantr @chizhg

### CODE REVIEW

**Comment by coryrc** [comment]
I'd rather keep them as executables so it's easier to transition to having all our tools in the [prow-tests](https://github.com/knative/test-infra/tree/master/images/prow-tests) image.

Can you instead update the `go install` or `go get` to get whichever copy you would otherwise be running?

**Comment by ian-mi** [comment]
I'm not sure I understand the requirement. I think we should always be building and running the vendored version of the generators rather than including them in the prow image.

**Comment by chizhg** [comment]
> I'd rather keep them as executables so it's easier to transition to having all our tools in the [prow-tests](https://github.com/knative/test-infra/tree/master/images/prow-tests) image.
> 
> Can you instead update the `go install` or `go get` to get whichever copy you would otherwise be running?

@coryrc this is not a tool maintained by EngProd and the version has to be consistent with the vendored k8s versions, so it does not make much sense to move it to `prow-tests` image.

/lgtm
/assign @mattmoor

File: hack/update-codegen.sh [hunk 1]
```diff
@@ -64,7 +64,7 @@ ${CODEGEN_PKG}/generate-groups.sh "deepcopy" \
   --go-header-file ${REPO_ROOT_DIR}/hack/boilerplate/boilerplate.go.txt
 
 # Depends on generate-groups.sh to install bin/deepcopy-gen
```
Comment (coryrc) [inline hack/update-codegen.sh:66]: Ah, now that I understand the requirement, you aren't using the vendored version here AFAICT, but whatever happens to be in `$GOPATH/src/k8s.io`, at least as far as I can understand from reading `go help packages`

It think should be `go run $(dirname $0)/../vendor/k8s.io/code-generator/cmd/deepcopy-gen`

The other instance happens to be okay because this is knative.dev/pkg... but you may want to change it to be consistent

**Comment by coryrc** [comment]
/hold
I don't think it will have the effect you desire (see comment I added)
But if you are sure, do /hold cancel

File: hack/generate-knative.sh [hunk 2]
```diff
@@ -89,7 +85,7 @@ if grep -qw "injection" <<<"${GENS}"; then
   # Clear old injection
   rm -rf ${OUTPUT_PKG}
 
-  ${GOPATH}/bin/injection-gen \
+  go run knative.dev/pkg/codegen/cmd/injection-gen \
```
Comment (mattmoor) [inline hack/generate-knative.sh:88]: I thought you had to pass the list of Go files to go run...

Comment (coryrc) [reply hack/generate-knative.sh:88]: directory is fine

File: hack/update-codegen.sh (hunk 1 above)
Comment (ian-mi) [reply hack/update-codegen.sh:66]: I'm not sure this is true. I tried removing code-generator from my GOPATH and the script succeeded without pulling code-generator back into GOPATH. Since the repo is now using go modules so GOPATH should not be used, and since the go.mod version is >= 1.14 go will default to running with -mod=vendor. Therefore go run should run by default using vendored modules. I also tested this by vendoring a change to deepcopy gen and checking for the changed output.

Comment (coryrc) [reply hack/update-codegen.sh:66]: okay, I forgot go modules affects a lot of functionality of go itself. Glad it worked!

Comment (n3wscott) [reply hack/update-codegen.sh:66]: vendor acts as GOPATH in go mod projects
