### PR TITLE
Fix race: Make informed watcher start wait for Add event 🏎️

### LINKED ISSUE #1960: Race condition when using config store backed by config maps
## Expected Behavior

When I try to use a config store backed by a config map immediately after the process using it starts up, when the config map exists before the process starts, I'd like to be able to guarantee that I am reading the configured value.

I think we could do this if one of the following was true:

1. When the reconciler starts, it could wait for the config store to be initialized, i.e. wait for the goroutines that handle events to fire at least once (see https://github.com/knative/pkg/issues/1907#issuecomment-733254238 for a description of this code) before returning
2. Provide a way for code using this reconciler to wait for this state (e.g. maybe don't do (1) by default, but at least provide a way for a caller to do this, e.g. [via the Reconciler object](https://github.com/tektoncd/pipeline/blob/8eaaeaac6957b7c7eff6694b00e792bc00f2c587/pkg/reconciler/taskrun/controller.go#L67-L79))
3. [Export the config store](https://github.com/knative/pkg/blob/a2394e88959df2ca1900855474ae43d7da0a9046/codegen/cmd/injection-gen/generators/reconciler_reconciler.go#L278-L280) so that I can look at the state

/kind bug

## Actual Behavior

When I use a generated reconciler, which has an unexported [configstore](https://github.com/knative/pkg/blob/a2394e88959df2ca1900855474ae43d7da0a9046/codegen/cmd/injection-gen/generators/reconciler_reconciler.go#L278-L280), if I try to back that config store with configmaps, there is a race condition where if I try to use that config store immediately after start up, the informed watcher's goroutines which read from the backing config maps and update the config store may not have fired yet, which means I might read something from the config store other than what I've configured.

## Steps to Reproduce the Problem

* I believe https://github.com/knative/pkg/issues/1907 was actually catching this bug (explanation at https://github.com/knative/pkg/issues/1907#issuecomment-733211228)
* I repro-ed this on the Tekton side with these horrible hacks: https://github.com/bobcatfish/pipeline/commit/1fbc3889b8ab1fbdcb2f0510a8c0674b436c3bf7 (trying to more reliably reproduce https://github.com/tektoncd/pipeline/issues/2815)

## Additional Info

* More detail from a Tekton perspective in https://github.com/tektoncd/pipeline/issues/2815#issuecomment-733207368

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

When using the informed watcher to watch a config map, previously add
events were being processed in a goroutine with no syncrhonization
making it so that code may try to access the values backed by the
configmaps before they are initialized.

This commit makes it so that the Start method of the informer will wait
for the add event to occur at least once for all config maps it is
watching.

This commit also undoes the workaround added in #1929 which was working
around the race condition identified in #1907 (and in
https://github.com/tektoncd/pipeline/issues/3720). This means that if
the synchronization was removed, the impacted test would start flaking
again. If we wanted it to reliably fail in that case, we could introduce
a sleep in the callback but that doesn't seem worth it.

I also tested this change by manually patching the changes into my
clone of tektoncd/pipeline and following the repro steps at
https://github.com/tektoncd/pipeline/issues/2815#issuecomment-733207368
Before the change I can reproduce the issue, and after the change, I
can't! :D

Fixes #1960 :bug:

@dprotaso @mattmoor 

/kind bug

**Release Note**

```release-note
Controllers built using knative/pkg and using the config store watcher for hot reloading of config maps can trust that once the controller has started, the values have been loaded from the backing config maps.
```

**Docs**

```docs
n/a
```

### CODE REVIEW

File: configmap/informer/informed_watcher.go [hunk 1]
```diff
@@ -207,3 +241,91 @@ func (i *InformedWatcher) deleteConfigMapEvent(obj interface{}) {
 	}
 	// If there is no default value, then don't do anything.
 }
+
```
Comment (bobcatfish) [inline configmap/informer/informed_watcher.go:244]: * I'm not sure if there is a better package to put these kind of synchronization primitives in?
* Instead of making these wrappers around a WaitGroup, I could use polling (e.g. like `cache.WaitForCacheSync(stopCh, i.informer.Informer().HasSynced)`) but using go synchronization primitives to do synchronization between goroutines seemed like a better solution to me (less consistent with the surrounding code tho)

**Comment by bobcatfish** [comment]
I can't tell if the pull-knative-pkg-unit-tests failure is legit 🤔

**Comment by bobcatfish** [comment]
image

image

File: configmap/informer/informed_watcher.go [hunk 2]
```diff
@@ -126,31 +130,56 @@ func (i *InformedWatcher) WatchWithDefault(cm corev1.ConfigMap, o ...configmap.O
...
 		return errors.New("error waiting for ConfigMap informer to sync")
 	}
 
-	return i.checkObservedResourcesExist()
+	if err := i.checkObservedResourcesExist(); err != nil {
+		return err
+	}
+
+	// Wait until all config maps have been at least initially processed
+	return s.WaitForAllKeys(stopCh)
```
Comment (dprotaso) [inline configmap/informer/informed_watcher.go:179]: This changes the contract a bit since prior you could run this watcher with supplied defaults and/or missing config maps.

I think being stricter is good but we should document this in the godoc

**Review by dprotaso — CHANGES_REQUESTED** [review]

**Comment by dprotaso** [comment]
Thanks for the PR! Yeah metrics tests are flakey

File: configmap/informer/informed_watcher.go [hunk 3]
```diff
@@ -126,31 +130,56 @@ func (i *InformedWatcher) WatchWithDefault(cm corev1.ConfigMap, o ...configmap.O
...
+	// to wait for the add event to be processed for all configmaps
+	s := NewSyncedCallback(i.getConfigMapNames(), i.addConfigMapEvent)
+	addConfigMapEvent := func(obj interface{}) {
+		configMap := obj.(*corev1.ConfigMap)
+		s.Call(obj, configMap.Name)
+	}
+	// Pretend that all the defaulted ConfigMaps were just created. This is done before we start
+	// the informer to ensure that if a defaulted ConfigMap does exist, then the real value is
+	// processed after the default one.
+	i.triggerAddEventForDefaultedConfigMaps(addConfigMapEvent)
```
[the remark this answers is not in the document]
Comment (bobcatfish) [reply configmap/informer/informed_watcher.go:163]: right, that's the case but only when using defaulted config maps - i wasnt totally clear on the expectations when using defaulted them, does this match what you think it should do? (i can add some comments at least explaining this if you can confirm this is what we want)

it DOES wait when you're not using defaulted config maps (e.g. in tekton pipelines afaik we're not using defaulted configmaps: https://github.com/tektoncd/pipeline/blob/93e368dbcb014e8650a6ba8ad01ca3c5f6eb6554/vendor/knative.dev/pkg/configmap/store.go#L114)

File: configmap/informer/informed_watcher.go (hunk 2 above)
Comment (bobcatfish) [reply configmap/informer/informed_watcher.go:179]: i'm not sure the contract has changed:

* if you supply defaults, it won't wait (as you commented above) (verified via [TestWatchMissingOKWithDefaultOnStart](https://github.com/knative/pkg/blob/8a8de5fc8c72f358ad3e7b5e29f4dfb8a264892d/configmap/informer/informed_watcher_test.go#L300)
* if you don't supply the config maps it expects, it'll fail before this change (checkObservedResourcesExist will return an error i think?), i think [TestWatchMissingFailsOnStart](https://github.com/knative/pkg/blob/8a8de5fc8c72f358ad3e7b5e29f4dfb8a264892d/configmap/informer/informed_watcher_test.go#L229) verifies that

File: configmap/informer/informed_watcher.go (hunk 1 above)
Comment (bobcatfish) [reply configmap/informer/informed_watcher.go:240]: writing tests for unexported code gives me a no feeling but i can understand why you dont want ppl to start importing this and relying on it :D

**Comment by bobcatfish** [comment]
should be ready for another look @dprotaso !

File: configmap/informer/informed_watcher.go (hunk 2 above)
Comment (dprotaso) [reply configmap/informer/informed_watcher.go:175]: I missed the `checkObservedResourcesExist` bit - thanks for pointing that out

File: configmap/informer/informed_watcher.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (dprotaso) [reply configmap/informer/informed_watcher.go:159]: I'm good with what you described - ie. if you include defaulted config maps then we don't wait for a sync from the API

Can you add the comment to both `Start` & `WatchWithDefault` ?

File: configmap/informer/informed_watcher_test.go [hunk 4]
```diff
@@ -18,18 +18,15 @@ package informer
...
 	corev1 "k8s.io/api/core/v1"
 	"k8s.io/apimachinery/pkg/api/equality"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/apimachinery/pkg/labels"
 	"k8s.io/apimachinery/pkg/runtime"
 	"k8s.io/apimachinery/pkg/selection"
-	"k8s.io/apimachinery/pkg/util/wait"
 	fakekubeclientset "k8s.io/client-go/kubernetes/fake"
+	"sync"
+	"testing"
```
Comment (dprotaso) [inline configmap/informer/informed_watcher_test.go:29]: run `goimports` here

Comment (bobcatfish) [reply configmap/informer/informed_watcher_test.go:29]: booo whoops

**Comment by bobcatfish** [comment]
@dprotaso I've updated the comments, lemme know what you think!

**Review by dprotaso — APPROVED** [review]
thanks for the changes!
